[plugins]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.ni]
github = 'azu/ni.zsh'

[plugins.fast-syntax-highlighting]
github = "zdharma/fast-syntax-highlighting"
#cmd by: sheldon add --github zdharma/fast-syntax-highlighting fast-syntax-highlighting
